clarify spec, fixing rspec warning
this test was passing, but because it was matching any error, it was
allowing broken behavior:

WARNING: Using the `raise_error` matcher without providing a specific error or message risks false positives, since `raise_error` will match when Ruby raises a `NoMethodError`, `NameError` or `ArgumentError`, potentially allowing the
expectation to pass without even executing the method you are intending to call. Actual error raised was #<NoMethodError: undefined method `[]' for nil:NilClass>. Instead consider providing a specific error class or message.